[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "nginx -g 'daemon off;'"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
